org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Using compileSdk=35 with AGP 8.5.x triggers a warning; suppress it.
android.suppressUnsupportedCompileSdk=35

# App Versioning
VERSION_CODE=7
VERSION_NAME=0.7.3

# GitHub Repository Info
GITHUB_REPO_OWNER=sudo-ajayverse
GITHUB_REPO_NAME=QuickDROP-App
