org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Using compileSdk=35 with AGP 8.5.x triggers a warning; suppress it.
android.suppressUnsupportedCompileSdk=35

# App Versioning
VERSION_CODE=7
VERSION_NAME=0.7.3

# GitHub Repository Info
GITHUB_REPO_OWNER=sudo-ajayverse
GITHUB_REPO_NAME=QuickDROP-App

# Supabase Credentials (Hardcoded for private project)
SUPABASE_URL=https://llxmpzutwtuytcgtlskc.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxseG1wenV0d3R1eXRjZ3Rsc2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0Mjk2ODEsImV4cCI6MjA4NzAwNTY4MX0.a-x8bi5uDtkUGR-d7NBsfwMOEYftju7b91IzgDIcPCA
SUPABASE_BUCKET=files
SUPABASE_FILES_TABLE=files
